# action.yml
name: 'Flyway Migrate'
description: 'Run SQL scripts on database'
inputs:
  url:
    description: The jdbc url to use to connect to the database
    required: true
  user:
    description: The user to use to connect to the database
    required: true
  password:
    description: The password to use to connect to the database
    required: true
  locations:
    description: Comma-separated list of locations to scan recursively for migrations
    required: true
    default: filesystem:./sql
  out_of_order:
    description: Support out of order migrations
    required: true
    default: "true"
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: docker://flyway/flyway:latest
  env:
    FLYWAY_URL: ${{ inputs.url }}
    FLYWAY_USER: ${{ inputs.user }}
    FLYWAY_PASSWORD: ${{ inputs.password }}
    FLYWAY_LOCATIONS: ${{ inputs.locations }}
    FLYWAY_OUT_OF_ORDER: ${{ inputs.out_of_order }}
  args:
    - migrate